// react/components/Profile.js
import React from 'react';
import ReactRouter, {Link} from 'react-router';
import GraphContainer from '../containers/GraphContainer'
import Moment from 'moment';

Moment.locale('nb');

const Profile = ({loggOutButton, name, date, posts, comments, image, last_visited}) => (  <div className="content">
    <div className="title">
        <h2>Min side</h2>
    </div>

    <div className="personalInfoContainer">
      <div className="personalInfo">

        <div className="profilePicture">
          <img src={image} alt="Profile"/>
        </div>

        <div className="information">
          <p>Navn: {name}</p>
          <p>Bruker opprettet: {Moment(date).fromNow()}</p>
          <br/>
          <p>Antall innlegg skrevet: {posts}</p>
          <p>Antall kommentarer skrevet: {comments}</p>
        </div>

      </div>

      <div className="logout">
        {loggOutButton ? <Link to="/"><div className="logoutButton">Logg ut</div></Link> : null}
      </div>
    </div>

    <div className="stats">
      <div className="lastVisited">
        <h2>Sist besøkte innlegg</h2>
        <ul className="lastVisitedList">
        {last_visited.map((last)=>(
          <li key={last._id}><Link to={"/posts/" + last._id}><span>{last.title}</span></Link></li>
          )
        )}
        </ul>
      </div>

      <div className="contributionGraph">
        <h2>Bidrag per måned</h2>
        <GraphContainer />
      </div>
    </div>
  </div>
);

export default Profile;

// angular/app/components/profile/profile.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'profile',
  template: `
  
  		<div>it!</div>
    
  `
})
export class ProfileComponent{
	
}
<div *ngIf='userprofile'>
  <div class='top'>
    <h2> Min side! </h2>
    <a routerLink="" class="logOutButton">Logg ut</a>
  </div>
  <div class='row'>
    <img src={{userprofile.image_src}} alt='profile image'/>
    <div class='profileInfo'>
      Navn: {{userprofile.name}}
      Bruker opprettet: {{userprofile.created_date}}
      <br>
      Antall innlegg skrevet: {{userprofile.num_posts}}
      Antall kommentarer skrevet: {{userprofile.num_comments}}
    </div>
  </div>
  <div class='row'>
    <div class='profileInfo'>
      <h2> Siste innlegg </h2>
      <div *ngFor='let post of userprofile.posts'>
      {{post.heading}}
      </div>
    </div>
    <div class='profileInfo'>
      <h2> Bidrag per måned </h2>
      Graf
    </div>
  </div>
</div>
